# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [284]:
# Import here.

import pandas as pd

import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

In [102]:
# Load the Food choices data set into a variable (e.g., df_food).



df_food = pd.read_csv("/workspaces/ds-dev-fall-2025/Week-02-Pandas-Part-2-and-DS-Overview/data/food_coded.csv")

df_food

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,3.5,1,1,610,4.0,420.0,2,"wine. mac and cheese, pizza, ice cream",boredom and sadness,NaN,...,1.0,1.0,5,940.0,500,Softball,5,1,1315,156
121,3,1,1,265,2.0,315.0,2,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,NaN,...,1.0,NaN,4,940.0,500,basketball,5,2,1315,180
122,3.882,1,1,720,NaN,420.0,1,"rice, potato, seaweed soup",sadness,NaN,...,1.0,2.0,5,580.0,690,none,4,2,1315,120
123,3,2,1,720,4.0,420.0,1,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods",NaN,...,2.0,2.0,1,940.0,500,NaN,3,1,1315,135
124,3.9,1,1,430,NaN,315.0,2,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",NaN,...,1.0,2.0,2,725.0,345,NaN,4,2,575,135

### Explore the Data

How much data did you just load?

In [4]:
# Count by hand. (lol kidding)

print(df_food.size)

print(df_food.info())

7625
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           123 non-null    object
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    object
 8   comfort_food_reasons          123 non-null    object
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    object
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    object
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    object
 25  fav_cuisine                   123 non-null    object
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    object
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    object
 35  ideal_diet                    124 non-null    object
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    object
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    object
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   99 non-null     object
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        123 non-null    object
dtypes: float64(20), int64(27), object(14)
memory usage: 59.7+ KB
None

What are the columns and their types in this data set?

In [16]:
# Show the column names and their types.

print(list(df_food.columns))

df_food.dtypes

['GPA', 'Gender', 'breakfast', 'calories_chicken', 'calories_day', 'calories_scone', 'coffee', 'comfort_food', 'comfort_food_reasons', 'comfort_food_reasons_coded', 'cook', 'comfort_food_reasons_coded.1', 'cuisine', 'diet_current', 'diet_current_coded', 'drink', 'eating_changes', 'eating_changes_coded', 'eating_changes_coded1', 'eating_out', 'employment', 'ethnic_food', 'exercise', 'father_education', 'father_profession', 'fav_cuisine', 'fav_cuisine_coded', 'fav_food', 'food_childhood', 'fries', 'fruit_day', 'grade_level', 'greek_food', 'healthy_feeling', 'healthy_meal', 'ideal_diet', 'ideal_diet_coded', 'income', 'indian_food', 'italian_food', 'life_rewarding', 'marital_status', 'meals_dinner_friend', 'mother_education', 'mother_profession', 'nutritional_check', 'on_off_campus', 'parents_cook', 'pay_meal_out', 'persian_food', 'self_perception_weight', 'soup', 'sports', 'thai_food', 'tortilla_calories', 'turkey_calories', 'type_sports', 'veggies_day', 'vitamins', 'waffle_calories', 'weight']

GPA                  object
Gender                int64
breakfast             int64
calories_chicken      int64
calories_day        float64
                     ...
type_sports          object
veggies_day           int64
vitamins              int64
waffle_calories       int64
weight               object
Length: 61, dtype: object

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns?

In [103]:
# Remove ‘em.
df_food = df_food.loc[:, df_food.columns.str.contains("calories|weight|gender", case=False)]
df_food

,Gender,calories_chicken,calories_day,calories_scone,self_perception_weight,tortilla_calories,turkey_calories,waffle_calories,weight
0,2,430,NaN,315.0,3.0,1165.0,345,1315,187
1,1,610,3.0,420.0,3.0,725.0,690,900,155
2,1,720,4.0,420.0,6.0,1165.0,500,900,I'm not answering this.
3,1,430,3.0,420.0,5.0,725.0,690,1315,"Not sure, 240"
4,1,720,2.0,420.0,4.0,940.0,500,760,190
...,...,...,...,...,...,...,...,...,...
120,1,610,4.0,420.0,4.0,940.0,500,1315,156
121,1,265,2.0,315.0,4.0,940.0,500,1315,180
122,1,720,NaN,420.0,4.0,580.0,690,1315,120
123,2,720,4.0,420.0,2.0,940.0,500,1315,135
124,1,430,NaN,315.0,3.0,725.0,345,575,135

What about `NaN`s? How many are there?

In [71]:
# Count ‘em.



df_food.isna().sum()

Gender                     0
calories_chicken           0
calories_day              19
calories_scone             1
self_perception_weight     1
tortilla_calories          1
turkey_calories            0
waffle_calories            0
weight                     2
dtype: int64

We gotta remove those `NaN`s―the entire row.

In [104]:
# Drop ‘em.

df_food["calories_day"] = df_food["calories_day"].fillna(0)
df_food["calories_scone"] = df_food["calories_scone"].fillna(0)
df_food["self_perception_weight"] = df_food["self_perception_weight"].fillna(0)
df_food["tortilla_calories"] = df_food["tortilla_calories"].fillna(0)
df_food

/tmp/ipykernel_2334/192462181.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_food["calories_day"] = df_food["calories_day"].fillna(0)
/tmp/ipykernel_2334/192462181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_food["calories_scone"] = df_food["calories_scone"].fillna(0)
/tmp/ipykernel_2334/192462181.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_food["self_perception_weight"] = df_food["self_perception_weight"].fillna(0)
/tmp/ipykernel_2334/192462181.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_food["tortilla_calories"] = df_food["tortilla_calories"].fillna(0)

,Gender,calories_chicken,calories_day,calories_scone,self_perception_weight,tortilla_calories,turkey_calories,waffle_calories,weight
0,2,430,0.0,315.0,3.0,1165.0,345,1315,187
1,1,610,3.0,420.0,3.0,725.0,690,900,155
2,1,720,4.0,420.0,6.0,1165.0,500,900,I'm not answering this.
3,1,430,3.0,420.0,5.0,725.0,690,1315,"Not sure, 240"
4,1,720,2.0,420.0,4.0,940.0,500,760,190
...,...,...,...,...,...,...,...,...,...
120,1,610,4.0,420.0,4.0,940.0,500,1315,156
121,1,265,2.0,315.0,4.0,940.0,500,1315,180
122,1,720,0.0,420.0,4.0,580.0,690,1315,120
123,2,720,4.0,420.0,2.0,940.0,500,1315,135
124,1,430,0.0,315.0,3.0,725.0,345,575,135

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [107]:
# Fix that.

df_food["weight"] = pd.to_numeric(df_food["weight"], errors="coerce")
df_food = df_food.dropna(subset=["weight"])
df_food

/tmp/ipykernel_2334/2852220478.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_food["weight"] = pd.to_numeric(df_food["weight"], errors="coerce")

,Gender,calories_chicken,calories_day,calories_scone,self_perception_weight,tortilla_calories,turkey_calories,waffle_calories,weight
0,2,430,0.0,315.0,3.0,1165.0,345,1315,187.0
1,1,610,3.0,420.0,3.0,725.0,690,900,155.0
4,1,720,2.0,420.0,4.0,940.0,500,760,190.0
5,1,610,3.0,980.0,5.0,940.0,345,1315,190.0
6,2,610,3.0,420.0,4.0,940.0,690,1315,180.0
...,...,...,...,...,...,...,...,...,...
120,1,610,4.0,420.0,4.0,940.0,500,1315,156.0
121,1,265,2.0,315.0,4.0,940.0,500,1315,180.0
122,1,720,0.0,420.0,4.0,580.0,690,1315,120.0
123,2,720,4.0,420.0,2.0,940.0,500,1315,135.0
124,1,430,0.0,315.0,3.0,725.0,345,575,135.0

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [112]:
# Savey save!

df_food.to_csv("survey_cleaned_food_coded.csv", index=False)
df_food

,Gender,calories_chicken,calories_day,calories_scone,self_perception_weight,tortilla_calories,turkey_calories,waffle_calories,weight
0,2,430,0.0,315.0,3.0,1165.0,345,1315,187.0
1,1,610,3.0,420.0,3.0,725.0,690,900,155.0
4,1,720,2.0,420.0,4.0,940.0,500,760,190.0
5,1,610,3.0,980.0,5.0,940.0,345,1315,190.0
6,2,610,3.0,420.0,4.0,940.0,690,1315,180.0
...,...,...,...,...,...,...,...,...,...
120,1,610,4.0,420.0,4.0,940.0,500,1315,156.0
121,1,265,2.0,315.0,4.0,940.0,500,1315,180.0
122,1,720,0.0,420.0,4.0,580.0,690,1315,120.0
123,2,720,4.0,420.0,2.0,940.0,500,1315,135.0
124,1,430,0.0,315.0,3.0,725.0,345,575,135.0

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

In [285]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set into a variable (e.g., df_salary).

df_salary = pd.read_csv("/workspaces/ds-dev-fall-2025/Week-02-Pandas-Part-2-and-DS-Overview/data/ask_a_manager_salary_survey_2021_responses_form_responses_1.tsv", sep="\t", thousands=",")
df_salary

,Timestamp,How old are you?,What industry do you work in?,Job title,"If your job title needs additional context, please clarify here:","What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:","If your income needs additional context, please provide it here:",What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,What is your race? (Choose all that apply.)
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,55000,0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,54600,4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,34000,NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,62000,3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,60000,7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28057,7/12/2024 22:52:01,35-44,Health care,Veterinarian,NaN,135000,NaN,USD,NaN,NaN,United States,Missouri,Wentzville,11 - 20 years,11 - 20 years,"Professional degree (MD, JD, etc.)",Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,USA,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28059,7/24/2024 12:22:58,18-24,"Accounting, Banking & Finance",Risk Management Associate,NaN,1200,0.0,USD,NaN,NaN,Myanmar,Colorado,Yangon,2 - 4 years,2 - 4 years,Some college,Man,Asian or Asian American
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American
28061,8/20/2024 1:06:13,25-34,Health care,Clinical physiologist,NaN,1200000,NaN,Other,NGN,NaN,Nigeria,NaN,Lagos,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American

Was that hard? 🙃

#### rename the file to something that is better for all systems.  
* No spaces in filename (can use '_')
* all lower case

### Explore

You know the drill.

How much data did you just load?

In [286]:
# Count by hand. I’m dead serious.

df_salary.size

print(df_salary.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28062 entries, 0 to 28061
Data columns (total 18 columns):
 #   Column                                                                                                                                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                --------------  -----
 0   Timestamp                                                                                                                                                                                                                             28062 non-null  object
 1   How old are you?                                                                                                                                                                                                                      28062 non-null  object
 2   What industry do you work in?                                                                                                                                                                                                         27988 non-null  object
 3   Job title                                                                                                                                                                                                                             28061 non-null  object
 4   If your job title needs additional context, please clarify here:                                                                                                                                                                      7262 non-null   object
 5   What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)  28062 non-null  int64
 6   How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                        20766 non-null  float64
 7   Please indicate the currency                                                                                                                                                                                                          28062 non-null  object
 8   If "Other," please indicate the currency here:                                                                                                                                                                                        206 non-null    object
 9   If your income needs additional context, please provide it here:                                                                                                                                                                      3042 non-null   object
 10  What country do you work in?                                                                                                                                                                                                          28062 non-null  object
 11  If you're in the U.S., what state do you work in?                                                                                                                                                                                     23039 non-null  object
 12  What city do you work in?                                                                                                                                                                                                             27980 non-null  object
 13  How many years of professional work experience do you have overall?                                                                                                                                                                   28062 non-null  object
 14  How many years of professional work experience do you have in your field?                                                                                                                                                             28062 non-null  object
 15  What is your highest level of education completed?                                                                                                                                                                                    27840 non-null  object
 16  What is your gender?                                                                                                                                                                                                                  27891 non-null  object
 17  What is your race? (Choose all that apply.)                                                                                                                                                                                           27885 non-null  object
dtypes: float64(1), int64(1), object(16)
memory usage: 3.9+ MB
None

What are the columns and their types?

In [287]:
# Show the column names and their types.


print(list(df_salary.columns))

print(df_salary.dtypes)

['Timestamp', 'How old are you?', 'What industry do you work in?', 'Job title', 'If your job title needs additional context, please clarify here:', "What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)", 'How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.', 'Please indicate the currency', 'If "Other," please indicate the currency here: ', 'If your income needs additional context, please provide it here:', 'What country do you work in?', "If you're in the U.S., what state do you work in?", 'What city do you work in?', 'How many years of professional work experience do you have overall?', 'How many years of professional work experience do you have in your field?', 'What is your highest level of education completed?', 'What is your gender?', 'What is your race? (Choose all that apply.)']
Timestamp                                                                                                                                                                                                                                object
How old are you?                                                                                                                                                                                                                         object
What industry do you work in?                                                                                                                                                                                                            object
Job title                                                                                                                                                                                                                                object
If your job title needs additional context, please clarify here:                                                                                                                                                                         object
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)      int64
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                          float64
Please indicate the currency                                                                                                                                                                                                             object
If "Other," please indicate the currency here:                                                                                                                                                                                           object
If your income needs additional context, please provide it here:                                                                                                                                                                         object
What country do you work in?                                                                                                                                                                                                             object
If you're in the U.S., what state do you work in?                                                                                                                                                                                        object
What city do you work in?                                                                                                                                                                                                                object
How many years of professional work experience do you have overall?                                                                                                                                                                      object
How many years of professional work experience do you have in your field?                                                                                                                                                                object
What is your highest level of education completed?                                                                                                                                                                                       object
What is your gender?                                                                                                                                                                                                                     object
What is your race? (Choose all that apply.)                                                                                                                                                                                              object
dtype: object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [289]:
# Rename ‘em.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed, gender, race

df_salary.columns = [
    "timestamp", "age", "industry", "title", "title_context", 
    "salary", "additional_compensation", "currency", "other_currency", 
    "salary_context", "country", "state", "city", "total_yoe", 
    "field_yoe", "highest_education_completed", "gender", "race"
]

df_salary

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,55000,0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,54600,4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,34000,NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,62000,3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,60000,7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28057,7/12/2024 22:52:01,35-44,Health care,Veterinarian,NaN,135000,NaN,USD,NaN,NaN,United States,Missouri,Wentzville,11 - 20 years,11 - 20 years,"Professional degree (MD, JD, etc.)",Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,USA,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28059,7/24/2024 12:22:58,18-24,"Accounting, Banking & Finance",Risk Management Associate,NaN,1200,0.0,USD,NaN,NaN,Myanmar,Colorado,Yangon,2 - 4 years,2 - 4 years,Some college,Man,Asian or Asian American
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American
28061,8/20/2024 1:06:13,25-34,Health care,Clinical physiologist,NaN,1200000,NaN,Other,NGN,NaN,Nigeria,NaN,Lagos,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [292]:
# List the unique industries and a count of their instances.




df_salary["industry"].value_counts().head(5)

industry
Computing or Tech                       4699
Education (Higher Education)            2464
Nonprofits                              2419
Health care                             1896
Government and Public Administration    1889
Name: count, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new dataframe.

In [293]:
# Filtery filter. (Save it to a new variable, df_salary_tech.)

df_salary_tech = df_salary["industry"].value_counts().head(5).index
df_salary = df_salary[df_salary["industry"].isin(df_salary_tech)]
df_salary
df_salary.iloc[2000]

timestamp                                        4/27/2021 12:30:01
age                                                           45-54
industry                       Government and Public Administration
title                                           Senior Web Producer
title_context                                                   NaN
salary                                                       115000
additional_compensation                                         0.0
currency                                                        USD
other_currency                                                  NaN
salary_context                                                  NaN
country                                               United States
state                                                    Washington
city                                                        Seattle
total_yoe                                             21 - 30 years
field_yoe                                             21 - 30 years
highest_education_completed                          College degree
gender                                                        Woman
race                                                          White
Name: 4290, dtype: object

Do a sanity check to make sure that the only values you kept are the one you are filtered for.

In [294]:
# Sanity Check 


print(df_salary["industry"].value_counts())

industry
Computing or Tech                       4699
Education (Higher Education)            2464
Nonprofits                              2419
Health care                             1896
Government and Public Administration    1889
Name: count, dtype: int64

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [296]:
# Filtery filter for just the jobs that pay in USD!

df_salary_usd = df_salary[df_salary["currency"] == "USD"]

df_salary_usd

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,55000,0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,62000,3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
5,4/27/2021 11:02:46,25-34,Education (Higher Education),Scholarly Publishing Librarian,NaN,62000,NaN,USD,NaN,NaN,USA,New Hampshire,Hanover,8 - 10 years,2 - 4 years,Master's degree,Man,White
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,112000,10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
10,4/27/2021 11:03:03,25-34,Nonprofits,Office Manager,NaN,47500,0.0,USD,NaN,NaN,United States,NaN,"Boston, MA",5-7 years,5-7 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28051,7/1/2024 20:05:58,25-34,Computing or Tech,Junior data analyst,NaN,35000,15000.0,USD,NaN,NaN,Usa,Alabama,Alabama,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American
28052,7/3/2024 14:02:01,25-34,Computing or Tech,Senior Global Public Relations Manager,NaN,144000,15000.0,USD,NaN,NaN,Usa,Massachusetts,Boise-but remote. Company located in Boston,8 - 10 years,8 - 10 years,Master's degree,Woman,White
28057,7/12/2024 22:52:01,35-44,Health care,Veterinarian,NaN,135000,NaN,USD,NaN,NaN,United States,Missouri,Wentzville,11 - 20 years,11 - 20 years,"Professional degree (MD, JD, etc.)",Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,USA,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American

What we really want know is how each U.S. city pays in tech. What value in `country` represents the United States of America?

In [300]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.

country_counts = df_salary_usd["country"].value_counts()

print(country_counts.head(5))

country
United States     4318
USA               3813
US                1252
U.S.               292
United States      255
Name: count, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [302]:
# Replace them all with 'US'.

df_salary_usd["country"] = df_salary_usd["country"].replace(
    ["United States", "USA", "US", "U.S.", "United States "],
    "US"
)

df_salary_usd

/tmp/ipykernel_2334/3330463334.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_salary_usd["country"] = df_salary_usd["country"].replace(

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,55000,0.0,USD,NaN,NaN,US,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,62000,3000.0,USD,NaN,NaN,US,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
5,4/27/2021 11:02:46,25-34,Education (Higher Education),Scholarly Publishing Librarian,NaN,62000,NaN,USD,NaN,NaN,US,New Hampshire,Hanover,8 - 10 years,2 - 4 years,Master's degree,Man,White
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,112000,10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
10,4/27/2021 11:03:03,25-34,Nonprofits,Office Manager,NaN,47500,0.0,USD,NaN,NaN,US,NaN,"Boston, MA",5-7 years,5-7 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28051,7/1/2024 20:05:58,25-34,Computing or Tech,Junior data analyst,NaN,35000,15000.0,USD,NaN,NaN,Usa,Alabama,Alabama,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American
28052,7/3/2024 14:02:01,25-34,Computing or Tech,Senior Global Public Relations Manager,NaN,144000,15000.0,USD,NaN,NaN,Usa,Massachusetts,Boise-but remote. Company located in Boston,8 - 10 years,8 - 10 years,Master's degree,Woman,White
28057,7/12/2024 22:52:01,35-44,Health care,Veterinarian,NaN,135000,NaN,USD,NaN,NaN,US,Missouri,Wentzville,11 - 20 years,11 - 20 years,"Professional degree (MD, JD, etc.)",Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,US,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American

Have a look at the count of each unique country again now.

In [306]:
# Count again.

(df_salary_usd["country"] == "US").sum()

# (df_salary_usd["country"] != "US").sum()

np.int64(9930)

Did you notice anything interesting?

In [ ]:
# BONUS CREDIT: resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [ ]:

# BONUS CREDIT: if you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [307]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.


df_salary_usd["salary"] = pd.to_numeric(df_salary_usd["salary"], errors="coerce")


state_salary_stats = (
    df_salary_usd.groupby("state")["salary"]
    .agg(["min", "mean", "max"])
    .reset_index()
    .sort_values("mean", ascending=False)  # optional: sort by mean salary
)

print(state_salary_stats)

                               state     min      mean     max
46       Michigan, Texas, Washington  340000  340000.0  340000
31                     Indiana, Ohio  245000  245000.0  245000
11              California, Colorado  176000  176000.0  176000
25            Georgia, Massachusetts  175000  175000.0  175000
1      Alabama, District of Columbia  156000  156000.0  156000
..                               ...     ...       ...     ...
45          Michigan, South Carolina   51333   51333.0   51333
4                    Alabama, Oregon   50000   50000.0   50000
39                Maryland, Virginia   48000   48000.0   48000
62                  Ohio, Washington   43000   43000.0   43000
22  District of Columbia, Washington   35000   35000.0   35000

[81 rows x 4 columns]

/tmp/ipykernel_2334/3762438339.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_salary_usd["salary"] = pd.to_numeric(df_salary_usd["salary"], errors="coerce")

Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed.

In [ ]:
# Fix it.

Let’s try that again.

In [ ]:
# Try it again. Yeah!

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [313]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.

df_salary_usd["timestamp"] = pd.to_datetime(df_salary_usd["timestamp"], errors="coerce")

df_cleaned_salary = df_salary_usd[df_salary_usd["timestamp"].dt.year.isin([2021, 2022, 2023])]

df_cleaned_salary

df_cleaned_salary.to_csv("cleaned_salary.csv", index="False")

/tmp/ipykernel_2334/3881699402.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_salary_usd["timestamp"] = pd.to_datetime(df_salary_usd["timestamp"], errors="coerce")

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)